version: '3.6'

services:
  db:
    image: mariadb:latest
    volumes:
      - snb_db:/var/lib/mysql
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306  # cannot change this port to other number
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=snb
      - MYSQL_USER=snb_user
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=toor
    ports:
      - "3302:3306"
  redis:
    image: redis:latest
    hostname: redis
  web:
    restart: always
    environment:
      - NODE_ENV=production
      - RHOST=redis
      - SLEEP_LENGTH=5
    links:
      - db
    build: .
    command: bash -c "python3 manage.py migrate --noinput --settings=settings.development && python3 manage.py runserver 0.0.0.0:8080 --settings=settings.development"
    volumes:
      - .:/snowboard_stuff
    ports:
      - "8080:8080"
volumes:
  snb_db: