# Generated by Django 2.1.2 on 2018-11-10 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0002_auto_20160226_1747'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiredToken',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authtoken.Token')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_expired', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'expire_token',
            },
            bases=('authtoken.token',),
        ),
    ]
